"""Frozen V1 inter-module data contracts -- G2-D1 Driver Drowsiness Monitoring.

This module is the single source of truth for every arrow in the pipeline:

    CAMERA -> SG-1 -> SG-2 --+
                 \\-> SG-3 --+--> SG-4 -> SG-5 -> ALERT

Per the project guide (Lab 3 Interface Gate) every contract fixes six things,
and they are enforced here rather than left to prose:

    1. data type ........ the dataclasses below
    2. units ............ pixels / seconds / ratio, stated per field
    3. coord convention . pixels, origin TOP-LEFT of the FULL frame, x right, y down
    4. confidence ....... float in [0.0, 1.0]
    5. empty behaviour .. ALWAYS return the payload with valid=False and a reason.
                          Never return None. Never raise on "no face this frame".
    6. example payload .. interfaces/mock/*.json (generated by generate_mocks.py)

RULES
-----
* Nothing in here imports numpy, OpenCV or MediaPipe. Contracts must be
  importable and testable on any machine, including bare CI. Image arrays are
  typed ``Any`` and passed by reference, never serialised.
* Changing a field after the Lab 3 freeze requires team-level agreement and a
  SCHEMA_VERSION bump. See documentation/interface_change_policy.md.
* Downstream sub-groups must tolerate valid=False on every frame without
  crashing; that is what the contract tests assert.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from enum import Enum
from typing import Any

SCHEMA_VERSION = "1.0.1"

# Target capture format agreed with SG-6 (see Figma: CAMERA USB-UVC 30 FPS 720p).
TARGET_FPS = 30
TARGET_WIDTH = 1280
TARGET_HEIGHT = 720

# Landmark indexing convention. SG-1 emits the classic 68-point dlib/iBUG layout
# so SG-2 and SG-3 can hard-code slices. MediaPipe FaceMesh (468 pts) is mapped
# down to these 68 inside SG-1 -- downstream groups never see FaceMesh indices.
LANDMARK_COUNT = 68
# EYE SIDES ARE SUBJECT-RELATIVE, following the iBUG/300-W convention:
#   indices 36-41 are the DRIVER'S RIGHT eye, which in a non-mirrored frontal
#   frame appears on the LEFT side of the image;
#   indices 42-47 are the DRIVER'S LEFT eye, appearing on the image's right.
# Getting this backwards is the classic silent bug here, so FaceResult names its
# ROIs the same way: right_eye_roi <- 36:42, left_eye_roi <- 42:48.
# If SG-6 mirrors the preview for the driver, it must mirror ONLY the display,
# never the frame handed to SG-1.
RIGHT_EYE_IDX = (36, 37, 38, 39, 40, 41)     # driver's right eye, image-left
LEFT_EYE_IDX = (42, 43, 44, 45, 46, 47)      # driver's left eye, image-right
MOUTH_OUTER_IDX = tuple(range(48, 60))
MOUTH_INNER_IDX = tuple(range(60, 68))


# --------------------------------------------------------------------------- #
# Enums -- serialise as their string value, never as an int.
# --------------------------------------------------------------------------- #
class EyeState(str, Enum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    UNKNOWN = "UNKNOWN"      # no usable eye ROI this frame


class DrowsinessState(str, Enum):
    OK = "OK"
    WARN = "WARN"
    ALERT = "ALERT"


# --------------------------------------------------------------------------- #
# Geometry primitives
# --------------------------------------------------------------------------- #
@dataclass
class BBox:
    """Axis-aligned box in FULL-FRAME pixel coordinates, origin top-left.

    Half-open: covers x .. x+w-1 and y .. y+h-1. Always clipped to the frame.
    """

    x: int
    y: int
    w: int
    h: int

    def __post_init__(self) -> None:
        self.x, self.y = int(self.x), int(self.y)
        self.w, self.h = int(self.w), int(self.h)

    @property
    def area(self) -> int:
        return max(0, self.w) * max(0, self.h)

    def clip(self, width: int, height: int) -> BBox:
        """Return a copy clipped to a width x height frame."""
        x0 = max(0, min(self.x, width))
        y0 = max(0, min(self.y, height))
        x1 = max(x0, min(self.x + self.w, width))
        y1 = max(y0, min(self.y + self.h, height))
        return BBox(x0, y0, x1 - x0, y1 - y0)

    def is_valid(self) -> bool:
        return self.w > 0 and self.h > 0

    def to_list(self) -> list[int]:
        return [self.x, self.y, self.w, self.h]

    @classmethod
    def from_list(cls, v: list[int] | tuple[int, int, int, int]) -> BBox:
        return cls(int(v[0]), int(v[1]), int(v[2]), int(v[3]))


@dataclass
class Frame:
    """Camera output. Carried by reference -- NEVER serialised to JSON.

    image: uint8 array, shape (H, W, 3), channel order **BGR** (OpenCV native).
           SG-1 converts to RGB internally if its model needs it.
    """

    frame_id: int                 # monotonically increasing from 0
    timestamp: float              # seconds, time.monotonic() at capture
    image: Any = None             # numpy.ndarray (H, W, 3) uint8 BGR
    width: int = TARGET_WIDTH
    height: int = TARGET_HEIGHT


# --------------------------------------------------------------------------- #
# SG-1 -> SG-2, SG-3     "face_box + eye_ROIs / mouth_ROI + landmarks"
# --------------------------------------------------------------------------- #
@dataclass
class FaceResult:
    """SG-1 Driver Face & Landmark Detection output.

    One driver only: if several faces are detected, SG-1 returns the largest
    box (the driver) -- downstream groups never deal with multiple faces.
    """

    frame_id: int
    timestamp: float
    valid: bool = False
    reason: str = "not_processed"          # why invalid; "" when valid

    face_box: BBox | None = None
    # 68 (x, y) pairs in FULL-FRAME pixels, float -- sub-pixel allowed.
    landmarks: list[tuple[float, float]] = field(default_factory=list)
    left_eye_roi: BBox | None = None
    right_eye_roi: BBox | None = None
    mouth_roi: BBox | None = None

    confidence: float = 0.0               # [0, 1] detector confidence
    # Head pose, degrees, optional. None until SG-1 implements it; SG-4/SG-5
    # must treat None as "unknown", not as 0.
    yaw_deg: float | None = None
    pitch_deg: float | None = None
    roll_deg: float | None = None

    @classmethod
    def empty(cls, frame_id: int, timestamp: float, reason: str = "no_face") -> FaceResult:
        return cls(frame_id=frame_id, timestamp=timestamp, valid=False, reason=reason)


# --------------------------------------------------------------------------- #
# SG-2 -> SG-4           "eye_state + EAR float"
# --------------------------------------------------------------------------- #
@dataclass
class EyeResult:
    """SG-2 Eye State & Blink Analysis output."""

    frame_id: int
    timestamp: float
    valid: bool = False
    reason: str = "not_processed"

    ear_left: float | None = None          # Eye Aspect Ratio, dimensionless
    ear_right: float | None = None
    ear: float | None = None               # fused (mean of available eyes)
    eye_state: EyeState = EyeState.UNKNOWN
    blink_event: bool = False              # True on the frame a blink COMPLETES
    # Seconds the eyes have been continuously closed up to and including this
    # frame; 0.0 when open. SG-4 uses this for sustained-closure gating.
    closure_duration_s: float = 0.0
    confidence: float = 0.0

    @classmethod
    def empty(cls, frame_id: int, timestamp: float, reason: str = "no_eye_roi") -> EyeResult:
        return cls(frame_id=frame_id, timestamp=timestamp, valid=False, reason=reason)


# --------------------------------------------------------------------------- #
# SG-3 -> SG-4           "yawn_flag + MAR float"
# --------------------------------------------------------------------------- #
@dataclass
class YawnResult:
    """SG-3 Yawn & Facial-Cue Analysis output."""

    frame_id: int
    timestamp: float
    valid: bool = False
    reason: str = "not_processed"

    mar: float | None = None               # Mouth Aspect Ratio, dimensionless
    yawn_flag: bool = False                # mouth is wide open THIS frame
    yawn_event: bool = False               # True on the frame a yawn COMPLETES
    yawn_duration_s: float = 0.0           # length of the in-progress yawn
    confidence: float = 0.0

    @classmethod
    def empty(cls, frame_id: int, timestamp: float, reason: str = "no_mouth_roi") -> YawnResult:
        return cls(frame_id=frame_id, timestamp=timestamp, valid=False, reason=reason)


# --------------------------------------------------------------------------- #
# SG-4 -> SG-5           "drowsy_score 0 ... 1"
# --------------------------------------------------------------------------- #
@dataclass
class TemporalResult:
    """SG-4 Temporal Behaviour Analysis output.

    Converts frame-level cues into behaviour over a sliding window. All rates
    are per minute, extrapolated from the window -- state the window length so
    SG-5 can reason about confidence on a partially-filled window.
    """

    frame_id: int
    timestamp: float
    valid: bool = False
    reason: str = "not_processed"

    window_s: float = 0.0                  # length of the window actually used
    window_filled: bool = False            # False while warming up
    perclos: float = 0.0                   # [0, 1] fraction of window eyes closed
    blink_rate_per_min: float = 0.0
    yawn_rate_per_min: float = 0.0
    longest_closure_s: float = 0.0         # longest closure inside the window
    # Closure duration at the CURRENT frame; 0.0 the instant the eyes reopen.
    # Unlike longest_closure_s (any closure still inside the window), this drops
    # to 0 as soon as a closure ends, so SG-5 can release its sustained-closure
    # override once the eyes reopen instead of holding ALERT for a whole window.
    # Additive, safe-default field (schema 1.0.1): consumers that ignore it are
    # unaffected. See documentation/interface_change_policy.md.
    current_closure_s: float = 0.0
    avg_ear: float | None = None
    drowsy_score: float = 0.0              # [0, 1] fused evidence, 1 = most drowsy
    confidence: float = 0.0

    @classmethod
    def empty(cls, frame_id: int, timestamp: float, reason: str = "warming_up") -> TemporalResult:
        return cls(frame_id=frame_id, timestamp=timestamp, valid=False, reason=reason)


# --------------------------------------------------------------------------- #
# SG-5 -> ALERT / SG-6   "state"
# --------------------------------------------------------------------------- #
@dataclass
class DecisionResult:
    """SG-5 Drowsiness Decision & Alert Logic output -- the system's answer."""

    frame_id: int
    timestamp: float
    valid: bool = True                     # a decision always exists, even if OK
    reason: str = ""

    state: DrowsinessState = DrowsinessState.OK
    drowsy_score: float = 0.0              # [0, 1] score the state was taken from
    alert: bool = False                    # True only while state == ALERT
    # Human-readable justification for the demo overlay and failure analysis,
    # e.g. "PERCLOS 0.42 > 0.30 for 3.1 s". Graded under failure analysis.
    evidence: str = ""
    # Camera-capture -> decision wall-clock latency. SG-6 profiles this; the
    # Figma KPI is alert latency, so it is part of the contract, not a nicety.
    latency_ms: float | None = None

    @classmethod
    def empty(cls, frame_id: int, timestamp: float, reason: str = "no_input") -> DecisionResult:
        return cls(
            frame_id=frame_id, timestamp=timestamp, valid=False,
            reason=reason, state=DrowsinessState.OK,
        )


# --------------------------------------------------------------------------- #
# Serialisation helpers -- used by mocks, CI schema checks and result logs.
# --------------------------------------------------------------------------- #
_PAYLOADS: dict[str, type] = {
    "FaceResult": FaceResult,
    "EyeResult": EyeResult,
    "YawnResult": YawnResult,
    "TemporalResult": TemporalResult,
    "DecisionResult": DecisionResult,
}


def to_dict(payload: Any) -> dict:
    """Dataclass -> plain JSON-safe dict (BBox -> [x, y, w, h], Enum -> str)."""

    def _conv(v: Any) -> Any:
        if isinstance(v, Enum):
            return v.value
        if isinstance(v, dict):
            # a BBox already flattened by asdict()
            if set(v) == {"x", "y", "w", "h"}:
                return [v["x"], v["y"], v["w"], v["h"]]
            return {k: _conv(x) for k, x in v.items()}
        if isinstance(v, (list, tuple)):
            return [_conv(x) for x in v]
        return v

    out = {k: _conv(v) for k, v in asdict(payload).items()}
    out["_type"] = type(payload).__name__
    out["_schema_version"] = SCHEMA_VERSION
    return out


def from_dict(d: dict) -> Any:
    """Plain dict -> the dataclass named by ``_type``. Inverse of to_dict()."""
    name = d.get("_type")
    if name not in _PAYLOADS:
        raise ValueError(f"unknown payload _type={name!r}; expected one of {sorted(_PAYLOADS)}")
    ver = d.get("_schema_version")
    if ver != SCHEMA_VERSION:
        raise ValueError(
            f"schema version mismatch: payload is {ver!r}, this code is {SCHEMA_VERSION!r}. "
            "Re-generate mocks (python interfaces/mock/generate_mocks.py) or bump the contract."
        )
    cls = _PAYLOADS[name]
    kwargs = {k: v for k, v in d.items() if not k.startswith("_")}

    for key in ("face_box", "left_eye_roi", "right_eye_roi", "mouth_roi"):
        if kwargs.get(key) is not None:
            kwargs[key] = BBox.from_list(kwargs[key])
    if kwargs.get("landmarks"):
        kwargs["landmarks"] = [(float(p[0]), float(p[1])) for p in kwargs["landmarks"]]
    if kwargs.get("eye_state") is not None:
        kwargs["eye_state"] = EyeState(kwargs["eye_state"])
    if kwargs.get("state") is not None:
        kwargs["state"] = DrowsinessState(kwargs["state"])
    return cls(**kwargs)


def validate(payload: Any) -> list[str]:
    """Return a list of contract violations. Empty list == compliant.

    This is what the Lab 3 Interface Gate and the CI schema job check. Keep it
    cheap enough to call on every frame in debug mode.
    """
    errs: list[str] = []
    t = type(payload).__name__

    if getattr(payload, "frame_id", -1) < 0:
        errs.append("frame_id must be >= 0")
    if not isinstance(getattr(payload, "timestamp", None), (int, float)):
        errs.append("timestamp must be a float (seconds)")
    if not isinstance(getattr(payload, "valid", None), bool):
        errs.append("valid must be a bool")
    if not payload.valid and not payload.reason:
        errs.append("valid=False requires a non-empty reason (empty-behaviour rule)")

    conf = getattr(payload, "confidence", None)
    if conf is not None and not (0.0 <= float(conf) <= 1.0):
        errs.append(f"confidence {conf} outside [0, 1]")

    for name in ("face_box", "left_eye_roi", "right_eye_roi", "mouth_roi"):
        box = getattr(payload, name, None)
        if box is not None and not box.is_valid():
            errs.append(f"{name} has non-positive width/height: {box.to_list()}")

    if t == "FaceResult" and payload.valid:
        if payload.face_box is None:
            errs.append("valid FaceResult must carry a face_box")
        if len(payload.landmarks) != LANDMARK_COUNT:
            errs.append(f"expected {LANDMARK_COUNT} landmarks, got {len(payload.landmarks)}")

    if t == "EyeResult" and payload.valid:
        if payload.ear is None:
            errs.append("valid EyeResult must carry an ear value")
        if payload.eye_state is EyeState.UNKNOWN:
            errs.append("valid EyeResult must not report eye_state=UNKNOWN")
        if payload.closure_duration_s < 0:
            errs.append("closure_duration_s must be >= 0")

    if t == "YawnResult" and payload.valid and payload.mar is None:
        errs.append("valid YawnResult must carry a mar value")

    if t == "TemporalResult":
        if not (0.0 <= payload.perclos <= 1.0):
            errs.append(f"perclos {payload.perclos} outside [0, 1]")
        if not (0.0 <= payload.drowsy_score <= 1.0):
            errs.append(f"drowsy_score {payload.drowsy_score} outside [0, 1]")
        for r in ("blink_rate_per_min", "yawn_rate_per_min",
                  "longest_closure_s", "current_closure_s"):
            if getattr(payload, r) < 0:
                errs.append(f"{r} must be >= 0")

    if t == "DecisionResult":
        if not isinstance(payload.state, DrowsinessState):
            errs.append("state must be a DrowsinessState")
        if payload.alert != (payload.state is DrowsinessState.ALERT):
            errs.append("alert must be True if and only if state == ALERT")
        if not (0.0 <= payload.drowsy_score <= 1.0):
            errs.append(f"drowsy_score {payload.drowsy_score} outside [0, 1]")

    return errs


def assert_valid(payload: Any) -> None:
    """Raise ValueError if ``payload`` violates its contract."""
    errs = validate(payload)
    if errs:
        raise ValueError(f"{type(payload).__name__} contract violation: " + "; ".join(errs))
